language: cpp

before_script:
    - pwd
    - which sh

script: "cd test && sh ./.travis_build.sh"

branches:
    only:
        - master

notifications:
    recipients:
        - nikhilrp@stanford.edu
    email:
        on_success: change
        on_failure: always
